/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DirectoryIdRouteImport } from './routes/directory.$id'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIdRoute = DirectoryIdRouteImport.update({
  id: '/directory/$id',
  path: '/directory/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alumni': typeof AlumniRoute
  '/student': typeof StudentRoute
  '/directory/$id': typeof DirectoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alumni': typeof AlumniRoute
  '/student': typeof StudentRoute
  '/directory/$id': typeof DirectoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alumni': typeof AlumniRoute
  '/student': typeof StudentRoute
  '/directory/$id': typeof DirectoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alumni' | '/student' | '/directory/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alumni' | '/student' | '/directory/$id'
  id: '__root__' | '/' | '/alumni' | '/student' | '/directory/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlumniRoute: typeof AlumniRoute
  StudentRoute: typeof StudentRoute
  DirectoryIdRoute: typeof DirectoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/$id': {
      id: '/directory/$id'
      path: '/directory/$id'
      fullPath: '/directory/$id'
      preLoaderRoute: typeof DirectoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlumniRoute: AlumniRoute,
  StudentRoute: StudentRoute,
  DirectoryIdRoute: DirectoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
